"""empty message

Revision ID: 1e882adda91b
Revises: 39d1e6192503
Create Date: 2023-03-23 16:00:40.451096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e882adda91b'
down_revision = '39d1e6192503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('favorite_people', sa.Integer(), nullable=True))
    op.drop_constraint('favorites_favorite_planets_fkey', 'favorites', type_='foreignkey')
    op.drop_constraint('favorites_Favorite_people_fkey', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'people', ['favorite_people'], ['name'])
    op.create_foreign_key(None, 'favorites', 'planets', ['favorite_planets'], ['name'])
    op.drop_column('favorites', 'Favorite_people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('Favorite_people', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_Favorite_people_fkey', 'favorites', 'people', ['Favorite_people'], ['id'])
    op.create_foreign_key('favorites_favorite_planets_fkey', 'favorites', 'planets', ['favorite_planets'], ['id'])
    op.drop_column('favorites', 'favorite_people')
    # ### end Alembic commands ###
