"""empty message

Revision ID: 39d1e6192503
Revises: c484355a2521
Create Date: 2023-03-23 15:37:05.376527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d1e6192503'
down_revision = 'c484355a2521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('Favorite_people', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('favorite_planets', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'planets', ['favorite_planets'], ['id'])
    op.create_foreign_key(None, 'favorites', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'favorites', 'people', ['Favorite_people'], ['id'])
    op.drop_column('favorites', 'people_name')
    op.drop_column('favorites', 'planet_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('planet_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('favorites', sa.Column('people_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'user_id')
    op.drop_column('favorites', 'favorite_planets')
    op.drop_column('favorites', 'Favorite_people')
    # ### end Alembic commands ###
