"""empty message

Revision ID: ac2486fe6f33
Revises: 0750869e5abe
Create Date: 2023-03-28 15:31:39.714608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2486fe6f33'
down_revision = '0750869e5abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('People_name', sa.String(length=256), nullable=True))
    op.add_column('favorites', sa.Column('people_id', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('planet_name', sa.String(length=256), nullable=True))
    op.add_column('favorites', sa.Column('planets_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'favorites', ['id'])
    op.create_foreign_key(None, 'favorites', 'planets', ['planets_id'], ['id'])
    op.create_foreign_key(None, 'favorites', 'people', ['people_id'], ['id'])
    op.drop_column('favorites', 'people_name')
    op.drop_column('favorites', 'planets_name')
    op.create_unique_constraint(None, 'people', ['id'])
    op.create_unique_constraint(None, 'planets', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planets', type_='unique')
    op.drop_constraint(None, 'people', type_='unique')
    op.add_column('favorites', sa.Column('planets_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('favorites', sa.Column('people_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='unique')
    op.drop_column('favorites', 'planets_id')
    op.drop_column('favorites', 'planet_name')
    op.drop_column('favorites', 'people_id')
    op.drop_column('favorites', 'People_name')
    # ### end Alembic commands ###
