"""empty message

Revision ID: c484355a2521
Revises: 1d9c5fa18b88
Create Date: 2023-03-23 14:23:39.406662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c484355a2521'
down_revision = '1d9c5fa18b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('planet_name', sa.String(length=256), nullable=True),
    sa.Column('people_name', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'planets', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planets', type_='unique')
    op.drop_table('favorites')
    # ### end Alembic commands ###
